export const USstates = [
    "AK",
                                    "AL",
                                    "AR",
                                    "AS",
                                    "AZ",
                                    "CA",
                                    "CO",
                                    "CT",
                                    "DC",
                                    "DE",
                                    "FL",
                                    "GA",
                                    "GU",
                                    "HI",
                                    "IA",
                                    "ID",
                                    "IL",
                                    "IN",
                                    "KS",
                                    "KY",
                                    "LA",
                                    "MA",
                                    "MD",
                                    "ME",
                                    "MI",
                                    "MN",
                                    "MO",
                                    "MS",
                                    "MT",
                                    "NC",
                                    "ND",
                                    "NE",
                                    "NH",
                                    "NJ",
                                    "NM",
                                    "NV",
                                    "NY",
                                    "OH",
                                    "OK",
                                    "OR",
                                    "PA",
                                    "PR",
                                    "RI",
                                    "SC",
                                    "SD",
                                    "TN",
                                    "TX",
                                    "UT",
                                    "VA",
                                    "VI",
                                    "VT",
                                    "WA",
                                    "WI",
                                    "WV",
                                    "WY"
    
]

export const UKstates = [
    'Avon',
    'Bedfordshire',
    'Berkshire',
    'Buckinghamshire',
    'Cambridgeshire',
    'Cheshire',
    'Cleveland',
    'Cornwall',
    'Cumbria',
    'Derbyshire',
    'Devon',
    'Dorset',
    'Durham',
    'East Sussex',
    'Essex',
    'Gloucestershire',
    'Hampshire',
    'Herefordshire',
    'Hertfordshire',
    'Isle of Wight',
    'Kent',
    'Lancashire',
    'Leicestershire',
    'Lincolnshire',
    'London',
    'Merseyside',
    'Middlesex',
    'Norfolk',
    'Northamptonshire',
    'Northumberland',
    'North Humberside',
    'North Yorkshire',
    'Nottinghamshire',
    'Oxfordshire',
    'Rutland',
    'Shropshire',
    'Somerset',
    'South Humberside',
    'South Yorkshire',
    'Staffordshire',
    'Suffolk',
    'Surrey',
    'Tyne and Wear',
    'Warwickshire',
    'West Midlands',
    'West Sussex',
    'West Yorkshire',
    'Wiltshire',
    'Worcestershire'
]